version: '3.8'

services:
  # Production build
  app:
    build:
      context: .
      target: production
    ports:
      - "8080:80"
    container_name: property-app
    restart: unless-stopped

  # Development build (with hot reload)
  app-dev:
    build:
      context: .
      target: development
    ports:
      - "3001:3001"
    container_name: property-app-dev
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped 